### PR TITLE
css-only hamburger icon on mobile, adding full header nav links 

### PR DESCRIPTION
**Pull request by wsvincent**
...to the rest of the header

### CODE REVIEW

**Comment by jasonbriggs** [comment]
I think these are too tight
screen shot 2016-06-21 at 12 50 45 pm

**Comment by jasonbriggs** [comment]
It's impossible to reach the bottom of the menu options when the screen is not very high
screen shot 2016-06-21 at 12 51 47 pm
 (mobile, etc.)

**Comment by wsvincent** [comment]
@jasonbriggs Ready for review...

**Comment by jasonbriggs** [comment]
Nice work! 👍

**Pull request merged**
